In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
#! wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

In [3]:
#importing the required data 
df = pd.read_csv("car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
pd.__version__

'3.0.6'

In [5]:
df.shape

(10000, 11)

In [6]:
df["fuel_type"].nunique()

3

In [7]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [8]:
df["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

In [10]:
# median before filling nan
be_fillna_medi = df["horsepower"].median()
print(be_fillna_medi)

# median after filling nan with the most frequent value 
most_frequent = df["horsepower"].value_counts().max()
print(most_frequent)

df["horsepower"] = df["horsepower"].fillna(most_frequent)

af_fillna_medi = df["horsepower"].median()

print(af_fillna_medi)

254.0
174
252.0

In [15]:
cars_from_asia = df[df["origin"]=="Asia"]
cars_from_asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,174.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [17]:
cars_from_asia = cars_from_asia[["vehicle_weight","model_year"]]
first_7columns = cars_from_asia.head(7)

In [18]:
X = first_7columns.to_numpy()
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

In [38]:
Xtransport = X.transpose()
print(Xtransport)

[[4240 4310 4230 4420 3950 4750 4450]
 [1996 1992 1997 1978 2007 2021 2019]]

In [37]:
XTX = np.matmul(Xtransport,X)
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]

In [45]:
inverse_XTX = np.linalg.inv(XTX)
print(inverse_XTX)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [46]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [47]:
w = np.matmul(np.matmul(inverse_XTX,Xtransport),y)
print(w)

[0.13644777 0.2327492 ]

In [48]:
print(w.sum())

0.36919696904925486